CalendarUtils.php, models/forms/TaskFilter.php, resources/css/task.less, tests/codeception/unit/TaskQueryTest.php, widgets/search/DateFilter.php, widgets/search/TaskFilterNavigation.php, widgets/search/views/dateFilter.php, widgets/search/views/taskFilterNavigation.php
Added an option to filter tasks by start and end scheduled date.
=> Enh: Task time filter

resources/css/task.less, resources/js/humhub.task.list.js, widgets/lists/views/taskList.php, widgets/lists/views/taskListItem.php
Drag handle has been added beside the task and task-list titles.
=> Drag handle has been added beside the task and task-list titles.

messages/es/activities.php
=> Translate activities.php

components/StreamAction.php
The model is STATUS_COMPLETED, not FINISH
=> fix stream action

models/Task.php
Issue: https://github.com/humhub/humhub/issues/4428
=> Replace db Expression time now with func date()

docs/CHANGELOG.md, module.json, resources/js/humhub.task.list.js
Issue: https://github.com/humhub/humhub/issues/4716
=> Remove gap between comments

docs/CHANGELOG.md, module.json, views/list/edit.php
Issue: https://github.com/humhub/tasks/issues/146
=> Fix placeholder text

controllers/SearchController.php, docs/CHANGELOG.md
Issue: https://github.com/humhub/tasks/issues/150
=> Fix access to search profile tasks

tests/codeception/api/TaskCest.php
Issue: https://github.com/humhub/tasks/issues/153
=> Fix broken tests

controllers/ListController.php, controllers/TaskController.php, docs/CHANGELOG.md
Issue: https://github.com/humhub/cfiles/issues/114
=> Fix for PHP8 - Deprecate required parameters after optional parameters

Events.php, docs/CHANGELOG.md, models/Task.php, widgets/WallEntry.php, widgets/views/wallEntry.php
Issue: https://github.com/humhub/tasks/issues/159
=> Fix view access for non-members

Events.php, docs/CHANGELOG.md, views/task/edit-scheduling.php, widgets/search/TaskFilterNavigation.php
Issue: https://github.com/humhub/humhub/issues/4558
=> Deprecate CompatModuleManager

docs/CHANGELOG.md, models/Task.php, models/checklist/TaskItem.php
=> #167 added separator for concatenated search attributes

docs/CHANGELOG.md, models/forms/TaskForm.php, views/task/edit.php
Issue: https://github.com/humhub/tasks/issues/169
=> Activate tab with first error field on edit a task

controllers/TaskController.php
#179 - the issue
The ids I removed are not used in the functions anyway.
=> fix assigning users error 400

docs/CHANGELOG.md, widgets/lists/views/taskListItem.php
issue: https://github.com/humhub/tasks/issues/190
=> Fix wrong scheduling information for completed tasks

assets/Assets.php
Issue: https://github.com/humhub/tasks/issues/203
=> Use theme colors

assets/Assets.php
Fix visible style code on stream.
=> Fix additional style to hide from stream

docs/CHANGELOG.md, models/lists/TaskList.php, module.json, views/list/index.php
Issue: https://github.com/humhub/tasks/issues/205#issuecomment-1267140099
=> Hide empty list of completed tasks

docs/CHANGELOG.md, widgets/search/TaskFilterNavigation.php
Issue: https://github.com/humhub/tasks/issues/212
=> Fix filter "Overdue"

models/Task.php
Issue of loop loading on wall stream
=> Fix task permission checking

docs/CHANGELOG.md, widgets/TaskRoleInfoBox.php, widgets/views/taskInfoBox.php, widgets/views/wallEntry.php
https://github.com/humhub/tasks/issues/227
=> Set Icon color to @text-color-main (#555)

docs/CHANGELOG.md, module.json, widgets/TaskPicker.php
Related issue: https://github.com/humhub/calendar/pull/445
=> Fix replaced method `friendship\Module::isEnabled()`

Events.php, docs/CHANGELOG.md, models/SnippetModuleSettings.php
https://github.com/humhub/tasks/issues/229
=> Disable main navigation by default

controllers/ConfigContainerController.php
https://github.com/humhub/humhub-internal/issues/184
=> Improve container module settings

assets/Assets.php, docs/CHANGELOG.md, models/Task.php, views/task/task_header.php, widgets/TaskInfoBox.php, widgets/TaskRoleInfoBox.php, widgets/lists/views/taskDetails.php, widgets/lists/views/taskListItem.php, widgets/search/views/taskSearchListEntry.php, widgets/views/mailContentEntry.php, widgets/views/myTasks.php, widgets/views/taskInfoBox.php, widgets/views/wallEntry.php
https://github.com/humhub/humhub-internal/issues/360
=> Replace theme variables with CSS variables

docs/CHANGELOG.md, extensions/custom_pages/elements/TaskElement.php, module.json
https://github.com/humhub/custom-pages-internal/issues/87
=> Use content ID in the "Custom Pages" extension

docs/CHANGELOG.md, models/lists/TaskList.php, module.json, views/list/edit.php, views/task/task_header.php, widgets/checklist/views/taskChecklistItem.php, widgets/lists/CompletedTaskListView.php, widgets/lists/views/completedTaskListItem.php, widgets/lists/views/taskList.php
https://github.com/humhub/humhub-internal/issues/782#issuecomment-3245787075
=> Update tooltip to Bootstrap 5

.github/workflows/php-test-develop.yml, .github/workflows/php-test-master.yml, .github/workflows/php-test-min-version.yml, .github/workflows/php-test-next.yml, controllers/ChecklistController.php, docs/CHANGELOG.md
https://github.com/humhub/humhub-internal/issues/844
=>  Improved Module Test GitHub Actions
